name: chat_interface
description: Frontend for the Fajurion Chat Network.
publish_to: 'none'

version: 1.0.0-ALPHA

environment:
  sdk: '>=2.19.2'

dependencies:
  flutter:
    sdk: flutter
    
  flutter_animate: any
  get: any
  path_provider: any
  path: any
  drift: any
  sqlite3_flutter_libs: any
  logger: any
  web_socket_channel: any
  crypto: any
  http: any
  animations: any
  pointycastle: any
  livekit_client: any
  logging: any
  url_launcher: any
  flutter_webrtc: any
  record: any
  sodium_libs: ^2.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: any
  build_runner: any
  flutter_lints: any
  test: ^1.24.1

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto Mono
      fonts:
        - asset: assets/RobotoMono.ttf
    - family: Roboto
      fonts:
        - asset: assets/Roboto-Regular.ttf
    - family: Open Sans
      fonts:
        - asset: assets/OpenSans.ttf

  assets:
  - assets/img/
