[package]
name = "space-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alkali = "0.3.0"
base64 = "0.21.4"
cpal = "0.15.2"
libspaceship = { path = "../libspaceship" }
