name: chat_interface
description: Frontend for the Fajurion Chat Network.
publish_to: 'none'

version: 1.0.0-ALPHA

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  flutter_animate: any
  get: any
  path_provider: any
  path: any
  drift: any
  sqlite3_flutter_libs: any
  logger: any
  web_socket_channel: any
  crypto: any
  http: any
  animations: any
  pointycastle: any
  livekit_client: any
  logging: any
  url_launcher: any
  flutter_webrtc: any
  record: any
  sodium_libs: any
  ffi: any
  flutter_rust_bridge: any
  freezed_annotation: any
  file_selector: ^1.0.1
  drift_db_viewer: ^2.0.0
  smooth_scroll_multiplatform: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: any
  build_runner: any
  flutter_lints: any
  test: any
  ffigen: any
  freezed: any

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto Mono
      fonts:
        - asset: assets/RobotoMono.ttf
    - family: Roboto
      fonts:
        - asset: assets/Roboto-Regular.ttf
    - family: Open Sans
      fonts:
        - asset: assets/OpenSans.ttf

  assets:
  - assets/img/
